name: Deploy Frontend to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Frontend to Raspberry Pi
        run: |
          ssh -o StrictHostKeyChecking=no -T pi@eclipseboardgamecalculator.duckdns.org <<EOF
            cd /home/pi/Eclipse/EclipseBoardgameWebApp/
            git pull
            npm install
            npm run build
            rm -r ../EclipseBoardgameServer/dist
            mv dist ../EclipseBoardgameServer/
            sudo systemctl restart eclipseServer
          EOF
