name: Deploy WebApp build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build React App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Archive production artifacts
        run: tar -czf dist.tar.gz dist
        continue-on-error: true

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: eclipseWebAppdist
          path: dist.tar.gz
          overwrite: true

      - name: Trigger server deploy
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GA_SERVER_REPO_TRIGGER_TOKEN }}
          repository: voisinhugo/EclipseBoardgameServer
          event-type: frontend-build-finished
